use gas_data;

create table if not exists model_config_tb (
    id bigint unsigned not null auto_increment comment '主键ID',
    config_code varchar(64) not null comment '配置编码',
    config_name varchar(128) not null comment '配置名称',
    agent_code varchar(64) not null comment '智能体编码',
    scene_code varchar(32) not null comment '场景编码：WINTER_SUPPLY/MONTHLY_SALES/SHORT_CUSTOMER',
    enabled tinyint not null default 1 comment '是否启用',
    description varchar(500) default null comment '描述',
    create_time datetime not null default current_timestamp comment '创建时间',
    update_time datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    primary key (id),
    unique key uk_config_code (config_code),
    key idx_model_config_agent (agent_code, enabled),
    key idx_model_config_scene (scene_code, enabled)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='模型配置表';

create table if not exists model_config_scope_tb (
    id bigint unsigned not null auto_increment comment '主键ID',
    model_config_id bigint unsigned not null comment '模型配置ID',
    region_code varchar(32) default null comment '地区编码',
    industry_code varchar(32) default null comment '行业编码',
    customer_code varchar(64) default null comment '客户编码',
    enabled tinyint not null default 1 comment '是否启用',
    create_time datetime not null default current_timestamp comment '创建时间',
    primary key (id),
    key idx_model_config (model_config_id),
    key idx_region (region_code),
    key idx_customer (customer_code),
    key idx_scope_lookup (region_code, industry_code, customer_code, enabled)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='模型配置作用范围表';

create table if not exists model_train_config_tb (
    id bigint unsigned not null auto_increment comment '主键ID',
    config_code varchar(64) not null comment '配置编码',
    config_name varchar(128) not null comment '配置名称',
    agent_code varchar(64) not null comment '智能体编码',
    scope_type varchar(32) not null comment '作用范围：REGION/CUSTOMER/INDUSTRY/ALL',
    region_code varchar(64) default null comment '区域编号',
    region_name varchar(64) default null comment '区域名称',
    industry_code varchar(64) default null comment '行业编号',
    industry_name varchar(64) default null comment '行业名称',
    customer_code varchar(64) default null comment '客户编号',
    customer_name varchar(128) default null comment '客户名称',
    train_start_date varchar(32) default null comment '训练数据开始日期',
    train_end_date varchar(32) default null comment '训练数据结束日期',
    train_frequency varchar(32) default null comment '训练频率：DAILY/WEEKLY/MONTHLY/SEASONAL/MANUAL',
    auto_train tinyint not null default 1 comment '是否自动训练',
    enable_backtest tinyint not null default 1 comment '是否启用回测',
    backtest_window int default null comment '回测窗口',
    model_strategy varchar(64) default 'AUTO_BEST' comment '模型选择策略',
    biz_config_json json default null comment '业务训练参数',
    enabled tinyint not null default 1 comment '是否启用',
    remark varchar(512) default null comment '备注',
    created_by varchar(64) default null comment '创建人',
    created_by_name varchar(64) default null comment '创建人名称',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    primary key (id),
    unique key uk_train_config_code (config_code),
    key idx_train_config_agent (agent_code, enabled),
    key idx_train_config_scope (agent_code, scope_type, region_code, customer_code, industry_code)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='智能体训练配置表';

create table if not exists model_forecast_config_tb (
    id bigint unsigned not null auto_increment comment '主键ID',
    config_code varchar(64) not null comment '配置编码',
    config_name varchar(128) not null comment '配置名称',
    agent_code varchar(64) not null comment '智能体编码',
    scope_type varchar(32) not null comment '作用范围：REGION/CUSTOMER/INDUSTRY/ALL',
    region_code varchar(64) default null comment '区域编号',
    region_name varchar(64) default null comment '区域名称',
    industry_code varchar(64) default null comment '行业编号',
    industry_name varchar(64) default null comment '行业名称',
    customer_code varchar(64) default null comment '客户编号',
    customer_name varchar(128) default null comment '客户名称',
    forecast_start_date varchar(32) default null comment '预测开始日期',
    forecast_horizon int default null comment '预测步长',
    forecast_frequency varchar(32) default null comment '预测频率：DAILY/WEEKLY/MONTHLY/SEASONAL/MANUAL',
    auto_forecast tinyint not null default 1 comment '是否自动预测',
    train_config_code varchar(64) default null comment '关联训练配置',
    model_batch_no varchar(64) default null comment '指定模型批次，为空则取最新成功模型',
    weather_source varchar(64) default null comment '气象来源',
    biz_config_json json default null comment '业务预测参数',
    enabled tinyint not null default 1 comment '是否启用',
    remark varchar(512) default null comment '备注',
    created_by varchar(64) default null comment '创建人',
    created_by_name varchar(64) default null comment '创建人名称',
    created_at datetime not null default current_timestamp comment '创建时间',
    updated_at datetime not null default current_timestamp on update current_timestamp comment '更新时间',
    primary key (id),
    unique key uk_forecast_config_code (config_code),
    key idx_forecast_config_agent (agent_code, enabled),
    key idx_forecast_config_scope (agent_code, scope_type, region_code, customer_code, industry_code),
    key idx_forecast_config_train (train_config_code)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci comment='智能体预测配置表';
