<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>bio.drqi</groupId>
    <artifactId>gas-forecast</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>gas-forecast-common</module>
        <module>gas-forecast-system</module>
        <module>gas-forecast-bussiness</module>
        <module>gas-forecast-gateway</module>
        <module>gas-forecast-dao</module>
        <module>gas-forecast-startup</module>
    </modules>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring-boot.version>3.2.5</spring-boot.version>
        <mybatis-plus.version>3.5.7</mybatis-plus.version>
        <jsqlparser.version>4.9</jsqlparser.version>
        <lombok.version>1.18.34</lombok.version>
        <mysql-connector-j.version>8.3.0</mysql-connector-j.version>
        <spotless-maven-plugin.version>3.10.2</spotless-maven-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>bio.drqi</groupId>
                <artifactId>gas-forecast-common-core</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>bio.drqi</groupId>
                <artifactId>gas-forecast-common-web</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>bio.drqi</groupId>
                <artifactId>gas-forecast-common-security</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>bio.drqi</groupId>
                <artifactId>gas-forecast-common-cache</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>bio.drqi</groupId>
                <artifactId>gas-forecast-dao</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>bio.drqi</groupId>
                <artifactId>gas-forecast-bussiness</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>bio.drqi</groupId>
                <artifactId>gas-forecast-system</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
                <version>${spring-boot.version}</version>
            </dependency>
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>com.github.jsqlparser</groupId>
                <artifactId>jsqlparser</artifactId>
                <version>${jsqlparser.version}</version>
            </dependency>
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            <dependency>
                <groupId>com.mysql</groupId>
                <artifactId>mysql-connector-j</artifactId>
                <version>${mysql-connector-j.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-annotation</artifactId>
            <version>3.5.7</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-core</artifactId>
            <version>3.5.7</version>
            <scope>compile</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>com.diffplug.spotless</groupId>
                <artifactId>spotless-maven-plugin</artifactId>
                <version>${spotless-maven-plugin.version}</version>
                <configuration>
                    <java>
                        <includes>
                            <include>src/**/*.java</include>
                            <include>scripts/**/*.java</include>
                        </includes>
                        <palantirJavaFormat/>
                        <removeUnusedImports/>
                        <trimTrailingWhitespace/>
                        <endWithNewline/>
                    </java>
                </configuration>
                <executions>
                    <execution>
                        <id>spotless-check</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-maven-plugin</artifactId>
                    <version>${spring-boot.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
