import type { Component } from 'vue'
import {
  Aim,
  Bell,
  Box,
  Briefcase,
  Calendar,
  ChatDotRound,
  Clock,
  Coin,
  Collection,
  Connection,
  Coordinate,
  Cpu,
  DataAnalysis,
  DataBoard,
  DataLine,
  Delete,
  Document,
  Download,
  Edit,
  Files,
  Filter,
  Finished,
  Flag,
  Folder,
  Grid,
  Help,
  Histogram,
  House,
  InfoFilled,
  Key,
  List,
  Location,
  Lock,
  Management,
  MapLocation,
  Memo,
  Menu,
  Message,
  Monitor,
  Notebook,
  Odometer,
  OfficeBuilding,
  Operation,
  PieChart,
  Platform,
  Plus,
  Refresh,
  School,
  Search,
  SetUp,
  Setting,
  Star,
  Tickets,
  Tools,
  TrendCharts,
  Unlock,
  Upload,
  User,
  UserFilled,
  VideoPlay,
  Warning
} from '@element-plus/icons-vue'

export interface MenuIconOption {
  label: string
  value: string
  component: Component
}

export const menuIconOptions: MenuIconOption[] = [
  { label: '首页', value: 'House', component: House },
  { label: '智能计算', value: 'Cpu', component: Cpu },
  { label: '数据分析', value: 'DataAnalysis', component: DataAnalysis },
  { label: '数据看板', value: 'DataBoard', component: DataBoard },
  { label: '趋势图', value: 'TrendCharts', component: TrendCharts },
  { label: '数据曲线', value: 'DataLine', component: DataLine },
  { label: '柱状图', value: 'Histogram', component: Histogram },
  { label: '饼图', value: 'PieChart', component: PieChart },
  { label: '仪表盘', value: 'Odometer', component: Odometer },
  { label: '网格', value: 'Grid', component: Grid },
  { label: '目标', value: 'Aim', component: Aim },
  { label: '连接', value: 'Connection', component: Connection },
  { label: '平台', value: 'Platform', component: Platform },
  { label: '显示器', value: 'Monitor', component: Monitor },
  { label: '日历', value: 'Calendar', component: Calendar },
  { label: '时钟', value: 'Clock', component: Clock },
  { label: '区域', value: 'MapLocation', component: MapLocation },
  { label: '位置', value: 'Location', component: Location },
  { label: '坐标', value: 'Coordinate', component: Coordinate },
  { label: '用户', value: 'User', component: User },
  { label: '用户实心', value: 'UserFilled', component: UserFilled },
  { label: '组织机构', value: 'OfficeBuilding', component: OfficeBuilding },
  { label: '部门学校', value: 'School', component: School },
  { label: '公文包', value: 'Briefcase', component: Briefcase },
  { label: '菜单', value: 'Menu', component: Menu },
  { label: '列表', value: 'List', component: List },
  { label: '管理', value: 'Management', component: Management },
  { label: '设置', value: 'Setting', component: Setting },
  { label: '工具', value: 'Tools', component: Tools },
  { label: '操作', value: 'Operation', component: Operation },
  { label: '配置', value: 'SetUp', component: SetUp },
  { label: '文件夹', value: 'Folder', component: Folder },
  { label: '文件', value: 'Document', component: Document },
  { label: '多文件', value: 'Files', component: Files },
  { label: '笔记本', value: 'Notebook', component: Notebook },
  { label: '备忘录', value: 'Memo', component: Memo },
  { label: '票据', value: 'Tickets', component: Tickets },
  { label: '集合', value: 'Collection', component: Collection },
  { label: '模型盒子', value: 'Box', component: Box },
  { label: '权限钥匙', value: 'Key', component: Key },
  { label: '锁定', value: 'Lock', component: Lock },
  { label: '解锁', value: 'Unlock', component: Unlock },
  { label: '搜索', value: 'Search', component: Search },
  { label: '筛选', value: 'Filter', component: Filter },
  { label: '新增', value: 'Plus', component: Plus },
  { label: '编辑', value: 'Edit', component: Edit },
  { label: '删除', value: 'Delete', component: Delete },
  { label: '刷新', value: 'Refresh', component: Refresh },
  { label: '上传', value: 'Upload', component: Upload },
  { label: '下载', value: 'Download', component: Download },
  { label: '消息', value: 'Message', component: Message },
  { label: '会话', value: 'ChatDotRound', component: ChatDotRound },
  { label: '通知', value: 'Bell', component: Bell },
  { label: '运行', value: 'VideoPlay', component: VideoPlay },
  { label: '完成', value: 'Finished', component: Finished },
  { label: '警告', value: 'Warning', component: Warning },
  { label: '信息', value: 'InfoFilled', component: InfoFilled },
  { label: '帮助', value: 'Help', component: Help },
  { label: '收藏', value: 'Star', component: Star },
  { label: '标记', value: 'Flag', component: Flag },
  { label: '费用', value: 'Coin', component: Coin }
]

const menuIconMap = new Map(menuIconOptions.map((option) => [option.value, option.component]))

export const resolveMenuIcon = (name?: string | null): Component => menuIconMap.get(name || '') || Document
